DROP DATABASE IF EXISTS entrataUscita;
CREATE DATABASE entrataUscita;
USE entrataUscita;
CREATE TABLE passagio (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    COGNOME VARCHAR(255),
    MOTIVO VARCHAR(255),
    DATAOGGI DATE ,
    ORAENTRATA DATETIME ,
    ORAUSCITA DATETIME  
 
);
